### ISSUE TITLE
Application Config: Add new Parameter attenuationDurationThresholds

### ISSUE THREAD

**Issue by christian-kirschnick** [corona-warn-app/cwa-server#414]
Add a new parameter to the application configuration, called "attenuationDurationTresholds". With the help of this parameter, we will be able to calculate the overall risk factor much better.

Default values are: X=50, Y=70. There will be call with the RKI today night in which the values might be adjusted.

```yaml
attenuation-duration-thresholds:
  lower: 50
  upper: 70
```
