### ISSUE TITLE
Application Configuration: Add version update support

### ISSUE THREAD

**Issue by christian-kirschnick** [corona-warn-app/cwa-server#416]
We would like to keep the mobile application informed about new releases/current release of the app. This information can then be presented to the user, in order to ask for applying updates. 

We would like to add new fields to the application config (example values):
 
```yaml
app-version:
    ios:
        latest: 1.5.2
        min: 1.2.2
    android: 
        latest: 1.3.2
        min: 1.1.2
```

After downloading the config, the app checks whether the signature can be verified. If that is the case, it will get the current & min values from the config based on the target platform. 

This information can now be used to prompt users for updating the app. The values for the versions must follow semantic versioning.
