### ISSUE TITLE
Application Configuration: Attenuation Duration

### ISSUE THREAD

**Issue by christian-kirschnick** [corona-warn-app/cwa-server#428]
The RKI requested weighting parameters for the three buckets defined by the attenuation duration threshold. Add this to the attenuation duration configuration.

@michael-burwig 

```yaml
attenuation-duration:
  thresholds:
    lower: 50
    upper: 70
  weights:
    low: 1 # attenuation < 50 dB 
    mid: 0.5 # attenuation >50 dB && < 70 dB 
    high: 0 # attenuation > 70dB is ignored
```
