### ISSUE TITLE
Application Configuration: Attenuation Duration Enhancements

### ISSUE THREAD

**Issue by christian-kirschnick** [corona-warn-app/cwa-server#437]
We need two additional configuration variables for the attenuation duration, namely defaultBucketOffset and riskScoreNormalizationDivisor.

The target config should look like this:

```yaml
default-bucket-offset: 0 # discussed as W4
risk-score-normalization-divisor: 25 # discussed as W5 
thresholds:
  lower: 50
  upper: 70
weights:
  low: 1.0
  mid: 0.5
  high: 0.0
```

Value range for bucket offset: 0 or 1 (int)
risk score normalization divisor: 1...1000 (int)
