### ISSUE TITLE
No read timeout and connect timeout set on VerificationServerClient

### ISSUE THREAD

**Issue by RomanNess** [corona-warn-app/cwa-server#581]
## Current Implementation
No read and connect timeouts are set for communication to `cwa-verification-server`. The timeout defaults to 60 seconds.

## Suggested Enhancement
Set explicit timeouts in the `application.yaml`. We probably want connection and read timeouts that are in the range of 5-10 seconds similar to the config of [cwa-verification-portal](https://github.com/corona-warn-app/cwa-verification-portal/blob/c460acaac3001d430080eecde5f76d256f4bde82/src/main/resources/application.yml#L5-L10).

```
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
```

## Expected Benefits
Threads in `cwa-server` are no longer blocked for 60 seconds when `cwa-verification-server` gets super slow. Faster feedback in `cwa-server`, if `cwa-verification-server` is not responsive.
