### ISSUE TITLE
Add mobile configuration

### ISSUE THREAD

**Issue by christian-kirschnick** [corona-warn-app/cwa-server#78]
Mobile needs to be able to fetch additional configuration/settings from the server. The process should be similar to the exposure configuration.

Therefore, add a new app-config.yaml to the codebase. The app-config should contain

```yaml
risk_classes: 
  - 
    class: LOW
    max: 3
    min: 1
    uri: "https://www..."
  - 
    class: MID
    max: 5
    min: 3
    uri: "https://www..."
  - 
    class: HIGH
    max: 8
    min: 5
    uri: "https://www..."
```
We need validations & tests (also similar to exposure config). The YAML needs to be parsed to the proto message, so it can used in the distribution service for pushing to CDN.
